# docker-compose.offline.yml

services:
  # Fragments microservice API server
  fragment:
    # Use a proper init process (tini)
    init: true
    # Build the Docker Image using the Dockerfile
    # and current directory as the build context
    build: .