# docker-compose.yml
services:
  fragments:
    image: nbasoglu1/fragment:latest
    init: true
    ports:
      - '80:8080'
    environment:
      - NODE_ENV=production
      - HTPASSWD_FILE=tests/.htpasswd